### PR TITLE
Display IAM user profile information as JSON

### PR DESCRIPTION
**Pull request by pbyrne**
This allows other shell scripts to parse the output and make use of its information.

### CODE REVIEW

**Comment by anfleene** [comment]
@pbyrne this appears to work except it's adding a color character which makes it invalid json I think is probably more of a bug with Output.say though

```ruby
2.1.4 :001 > json = `bundle exec opsicle user-profile-info staging`
 => "{\"iam_user_arn\":\"arn:aws:iam::108064780585:user/andrew.fleener\",\"name\":\"andrew.fleener\",\"ssh_username\":\"andrewfleener\",\"ssh_public_key\":\"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+O1/rFEh91IXNg43a0jLiI6I3JH3Jc/QKv9JFXAmBlVPhJsc94ULY/4/Vs4mSQ5WYID+JU/O++I/IPs5e8Fdpp1imulut0+5qRp2YX6jD5/gOLgIKhlYbnviwykH5HQ6J3ZaiQFmlsRrjxfnrbaaxKiHUQfHA2lo2y+Eh7HxqEt5waGtQmI7iZVqqol/GHYOgXYP3UBSVdAoj7nNXI3Wd1saXFyC7DGwaPYztEBeNJauyAhkNufWfHqVtXKM2O+MJWYNWgA/ElnxRbgb555DK7oO7WKFI1lLmq5ciQjBuYE9IOSvjVE+5Ml8XKgjgHoFQLWwOBw1uuFrHauUPt+Yv anfleene@Andrews-MacBook-Air.local\"}\e[0m\n"

```

**Comment by NickLaMuro** [comment]
Ugh, that is what it was... I was trying to get this to parse and was getting no dice.  Regardless, you should make it machine parse-able, otherwise there is little value for this on it's own.

**Comment by pbyrne** [comment]
> except it's adding a color character which makes it invalid json

Oh, weird. I don't see that in the ZSH console or running it through `jq`, so I never noticed. But when I'm in Ruby, I saw the same thing you pasted. I've disabled it with https://github.com/pbyrne/opsicle/commit/7a4b02d04e99612a07236b82655610acd112b1ae, though there might be a better way to go about it.

**Comment by anfleene** [comment]
That works :+1:

**Comment by anfleene** [comment]
Thanks @pbyrne 0.16.0 is out on Rubygems

**Comment by pbyrne** [comment]
👏

**Pull request merged**
