### PR TITLE
Fix MFA deploy tracking bug

### PR DESCRIPTION
**Pull request by bbergstrom**
Description and Impact
----------------------
Fixes https://github.com/sportngin/opsicle/issues/82 by changing the config and client to re-use the session for the whole command.

Deploy Plan
-----------
> Does Platform Operations need to know anything special about this deploy? Are migrations present?

Rollback Plan
-------------
* To roll back this change, revert the merge with: `git revert -m 1 MERGE_SHA` and perform another deploy.

URLs
----
https://github.com/sportngin/opsicle/issues/82

QA Plan
-------
Put in a .opsicle file in the project for testing.
Use an environment with MFA configured.
Try deploy to verify bug is fixed.
`bundle exec opsicle --debug --verbose deploy staging`
Try other commands for regression.

### CODE REVIEW

**Comment by anfleene** [comment]
You should write a test or 2 for this :zap:

**Comment by bbergstrom** [comment]
@anfleene Revised.

**Comment by anfleene** [comment]
these code changes look good. @mkrieger you should QA this since you found the bug :+1:

**Comment by anfleene** [comment]
these code changes look good. @matthewrkrieger you should QA this since you found the bug :+1:

**Comment by anfleene** [comment]
these code changes look good. @matthewrkrieger you should QA this since you found the bug I can help you get setup to test it tomorrow.

**Comment by emmasax1** [comment]
QA is 👍 

screen shot 2016-05-20 at 10 53 57 am
resulted in:
screen shot 2016-05-20 at 10 53 50 am

**Pull request merged**
